FROM  centos
MAINTAINER QMJQ 20190926 http://qmjq.github.io

RUN mkdir -p /data/ipush/server  && mkdir -p /data/ipush/lib
RUN rm -rf /etc/localtime ;ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
COPY c_k8s/ipush/server /data/ipush/server
#COPY c_k8s/lib /data/ipush/lib

WORKDIR /data/ipush/server

#VOLUME  /root/ipush 

EXPOSE 2100

#ENTRYPOINT ["./ipush_server",">","/dev/null",">&1","&"]
CMD ["./ipush_server",">","/dev/null",">&1","&"]
