FROM  nginx
MAINTAINER QMJQ 20190926 http://qmjq.github.io

RUN mkdir -p /data/cm/server  && mkdir -p /data/cm/lib
RUN rm -rf /etc/nginx/conf.d ;ln -s -f /mnt/azure/nginx-php-swoole/cert  /etc/nginx/cert && ln -s -f /mnt/azure/nginx-php-swoole/conf.d  /etc/nginx/conf.d && ln -s -f /mnt/azure/nginx-php-swoole/nginx.conf  /etc/nginx/nginx.conf

WORKDIR /etc/nginx


EXPOSE 443

#ENTRYPOINT ["nginx", "-g", "daemon off;"]
CMD ["nginx", "-g", "daemon off;"]
