FROM harbor:80/front/packet
MAINTAINER QMJQ 20220801 jingge
WORKDIR /app/soft/nginx
#RUN  ln -sf /usr/share/zoneinfo/Asia/Chongqing /etc/localtime && rm -rf  html/*  conf/vhost/;
RUN  ln -sf /usr/share/zoneinfo/Asia/Chongqing /etc/localtime && rm -rf  html/*  conf/vhost/* && sed -i 's/worker_processes  auto/worker_processes  1/g' conf/nginx.conf;
ADD  ./*.proxy.conf conf/vhost/
COPY  ./dist html
EXPOSE 80
EXPOSE 443
CMD ["/app/soft/nginx/sbin/nginx", "-g", "daemon off;"]
