FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
MAINTAINER QMJQ 20220801 jingge
WORKDIR /app
EXPOSE 7076

COPY . /app
# install libgdiplus for System.Drawing

RUN apt-get update && apt-get install -y --allow-unauthenticated libgdiplus libc6-dev libgdiplus libx11-dev && rm -rf /var/lib/apt/lists/*
#Ê±ÇøÉèÖÃ
RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
&& echo 'Asia/Shanghai' >/etc/timezone

ENTRYPOINT ["dotnet", "Sjzy.Track.WebApi.dll"]
